#!/bin/sh
#
# generate deps.zip from wheels
# allows you to run a Python script without virtualenv
#
# make sure you can run pip wheel, zip and unzip
#
# 2017.02.17 darell tan
#

set -e

WHL_DIR=`mktemp -d /tmp/mkwheels.XXXXXXXXXX`
UNPACK_DIR=`mktemp -d /tmp/mkwheels2.XXXXXXXXXX`

cleanup() {
	[ -d "$WHL_DIR" ] && rm -rf "$WHL_DIR"
	[ -d "$UNPACK_DIR" ] && rm -rf "$UNPACK_DIR"
}

trap cleanup EXIT

# download required wheels
echo "downloading required wheels..."
pip wheel --wheel-dir=$WHL_DIR -r requirements.txt

echo "unpacking wheels..."
for whl in $WHL_DIR/*.whl; do
	unzip $whl -x "*.dist-info/*" -d $UNPACK_DIR
done

ZIPFILE=$PWD/deps.zip
echo "repacking into $ZIPFILE..."
(cd $UNPACK_DIR && zip $ZIPFILE -q -r .)

echo "done."

